package model;
// Generated Apr 13, 2018 1:39:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String idAdmin;
     private String namaAdmin;
     private String alamat;
     private String noTelp;
     private String email;
     private Set<Nasabah> nasabahs = new HashSet<Nasabah>(0);

    public Admin() {
    }

	
    public Admin(String idAdmin) {
        this.idAdmin = idAdmin;
    }
    public Admin(String idAdmin, String namaAdmin, String alamat, String noTelp, String email, Set<Nasabah> nasabahs) {
       this.idAdmin = idAdmin;
       this.namaAdmin = namaAdmin;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
       this.nasabahs = nasabahs;
    }
   
    public String getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(String idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getNamaAdmin() {
        return this.namaAdmin;
    }
    
    public void setNamaAdmin(String namaAdmin) {
        this.namaAdmin = namaAdmin;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Nasabah> getNasabahs() {
        return this.nasabahs;
    }
    
    public void setNasabahs(Set<Nasabah> nasabahs) {
        this.nasabahs = nasabahs;
    }




}


