package model;
// Generated Apr 13, 2018 1:39:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asuransi generated by hbm2java
 */
public class Asuransi  implements java.io.Serializable {


     private String idAsuransi;
     private String nmAsuransi;
     private Set<Pembayaran> pembayarans = new HashSet<Pembayaran>(0);

    public Asuransi() {
    }

	
    public Asuransi(String idAsuransi) {
        this.idAsuransi = idAsuransi;
    }
    public Asuransi(String idAsuransi, String nmAsuransi, Set<Pembayaran> pembayarans) {
       this.idAsuransi = idAsuransi;
       this.nmAsuransi = nmAsuransi;
       this.pembayarans = pembayarans;
    }
   
    public String getIdAsuransi() {
        return this.idAsuransi;
    }
    
    public void setIdAsuransi(String idAsuransi) {
        this.idAsuransi = idAsuransi;
    }
    public String getNmAsuransi() {
        return this.nmAsuransi;
    }
    
    public void setNmAsuransi(String nmAsuransi) {
        this.nmAsuransi = nmAsuransi;
    }
    public Set<Pembayaran> getPembayarans() {
        return this.pembayarans;
    }
    
    public void setPembayarans(Set<Pembayaran> pembayarans) {
        this.pembayarans = pembayarans;
    }




}


