package model;
// Generated Apr 13, 2018 1:39:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pembayaran generated by hbm2java
 */
public class Pembayaran  implements java.io.Serializable {


     private String noPembayaran;
     private Nasabah nasabah;
     private Asuransi asuransi;
     private Date tglPembayaran;
     private String jumlahBayar;

    public Pembayaran() {
    }

	
    public Pembayaran(String noPembayaran) {
        this.noPembayaran = noPembayaran;
    }
    public Pembayaran(String noPembayaran, Nasabah nasabah, Asuransi asuransi, Date tglPembayaran, String jumlahBayar) {
       this.noPembayaran = noPembayaran;
       this.nasabah = nasabah;
       this.asuransi = asuransi;
       this.tglPembayaran = tglPembayaran;
       this.jumlahBayar = jumlahBayar;
    }
   
    public String getNoPembayaran() {
        return this.noPembayaran;
    }
    
    public void setNoPembayaran(String noPembayaran) {
        this.noPembayaran = noPembayaran;
    }
    public Nasabah getNasabah() {
        return this.nasabah;
    }
    
    public void setNasabah(Nasabah nasabah) {
        this.nasabah = nasabah;
    }
    public Asuransi getAsuransi() {
        return this.asuransi;
    }
    
    public void setAsuransi(Asuransi asuransi) {
        this.asuransi = asuransi;
    }
    public Date getTglPembayaran() {
        return this.tglPembayaran;
    }
    
    public void setTglPembayaran(Date tglPembayaran) {
        this.tglPembayaran = tglPembayaran;
    }
    public String getJumlahBayar() {
        return this.jumlahBayar;
    }
    
    public void setJumlahBayar(String jumlahBayar) {
        this.jumlahBayar = jumlahBayar;
    }




}


